### ISSUE TITLE
Error while converting

### ISSUE THREAD

**Issue by xhn16729** [ed-asriyan/tgs-to-gif#2]
I got error while converting.
Did I miss something?
```
littlebear@littlebear:~/tgs-to-gif$ npm start .

> tgs-to-gif@0.0.1 start /home/littlebear/tgs-to-gif
> node index.js "."

Converting 2_1360886329340072453.tgs...
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
Emitted 'error' event on Gunzip instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at Gunzip.onerror (_stream_readable.js:764:9)
    at Gunzip.emit (events.js:321:20)
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tgs-to-gif@0.0.1 start: `node index.js "."`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tgs-to-gif@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/littlebear/.npm/_logs/2020-01-12T02_56_26_059Z-debug.log
```

**Comment by xhn16729** [comment]
Here's the debug log.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '.' ]
2 info using npm@6.13.4
3 info using node@v13.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tgs-to-gif@0.0.1~prestart: tgs-to-gif@0.0.1
6 info lifecycle tgs-to-gif@0.0.1~start: tgs-to-gif@0.0.1
7 verbose lifecycle tgs-to-gif@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle tgs-to-gif@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/littlebear/tgs-to-gif/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle tgs-to-gif@0.0.1~start: CWD: /home/littlebear/tgs-to-gif
10 silly lifecycle tgs-to-gif@0.0.1~start: Args: [ '-c', 'node index.js "."' ]
11 silly lifecycle tgs-to-gif@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle tgs-to-gif@0.0.1~start: Failed to exec start script
13 verbose stack Error: tgs-to-gif@0.0.1 start: `node index.js "."`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid tgs-to-gif@0.0.1
15 verbose cwd /home/littlebear/tgs-to-gif
16 verbose Linux 4.15.0-55-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "."
18 verbose node v13.6.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error tgs-to-gif@0.0.1 start: `node index.js "."`
22 error Exit status 1
23 error Failed at the tgs-to-gif@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by xhn16729** [comment]
I got the problem.

I was using the tgs file which was already decoded to json format. But the input file should be the binary tgs file.

Problem perfectly solved after I changed the input file to the binary one.
