### ISSUE TITLE
conversion error

### ISSUE THREAD

**Issue by veleg** [ed-asriyan/tgs-to-gif#39]
Using node cli.js 1.tgs
Returns an error. 
How to fix it,
```
(node:3718) DeprecationWarning: _ActionsContainer.addArgument() is renamed to _ActionsContainer.add_argument()
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:3718) DeprecationWarning: ArgumentParser.parseArgs() is renamed to ArgumentParser.parse_args()
/home/admin/web/swedart.ru/public_html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[0329/002301.725900:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/admin/web/swedart.ru/public_html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/admin/web/swedart.ru/public_html/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:381:22)
    at Interface.close (node:readline:514:8)
    at Socket.onend (node:readline:248:10)
    at Socket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

```

**Comment by ed-asriyan** [comment]
From your output:
> [0329/002301.725900:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180

By default tgs-to-gif runs chromium without `--no-sandbox` key:
https://github.com/ed-asriyan/tgs-to-gif/blob/a4640a5c7d0140561cd8e520e3b8cefb2af4516e/cli.js#L44

So, **to solve the issue set `USE_SANDBOX` env variable to `false`**:
```commandline
export USE_SANDBOX= false
```
