### ISSUE TITLE
Error: WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by arbarbosa1979** [ed-asriyan/tgs-to-gif#53]
**node version**: v17.1.0
**npm version**: 8.3.1

I am trying to run this converter, but on every attempt I get this error and nothing is converted.

```
Converting D:\Telegram Desktop\Animated\ytrfAnimatedSticker.tgs...
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (D:\tgs-to-gif\node_modules\ws\lib\websocket.js:329:19)
    at WebSocketTransport.send (D:\tgs-to-gif\node_modules\puppeteer\lib\WebSocketTransport.js:60:14)
    at Connection._rawSend (D:\tgs-to-gif\node_modules\puppeteer\lib\Connection.js:86:21)
    at Connection.send (D:\tgs-to-gif\node_modules\puppeteer\lib\Connection.js:72:21)
    at Browser._createPageInContext (D:\tgs-to-gif\node_modules\puppeteer\lib\Browser.js:174:47)
    at BrowserContext.newPage (D:\tgs-to-gif\node_modules\puppeteer\lib\Browser.js:367:26)
    at Browser.newPage (D:\tgs-to-gif\node_modules\puppeteer\lib\Browser.js:166:33)
    at Browser.<anonymous> (D:\tgs-to-gif\node_modules\puppeteer\lib\helper.js:112:23)
    at default (file:///D:/tgs-to-gif/render.js:81:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  -- ASYNC --
    at Browser.<anonymous> (D:\tgs-to-gif\node_modules\puppeteer\lib\helper.js:111:15)
    at default (file:///D:/tgs-to-gif/render.js:81:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/tgs-to-gif/index.js:55:50
    at async file:///D:/tgs-to-gif/index.js:37:20
    at async convertFiles (file:///D:/tgs-to-gif/cli.js:12:7)
    at async main (file:///D:/tgs-to-gif/cli.js:44:3)
    ```

**Comment by ed-asriyan** [comment]
not relevant since switch to c++ version
